baseURL = "https://pranavwillbreakit.github.io/"
languageCode = "en"
title = "Pranav will break it!"
DefaultContentLanguage = "en"

theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "I'm Pranav"
author = "Pranav Bansal"
description = "I break things for $"
profilePicture = "images/profile.jpg"
keywords = "QA,Testing,Freelancer"
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/pranav-bansal-756079118"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/pranavwillbreakit/"

# [[params.socialIcons]]
# icon = "fa-instagram"
# title = "instagram"
# url = "https://www.instagram.com/"

# [[params.socialIcons]]
# icon = "fa-envelope"
# title = "e-mail"
# url = "mailto:mail@alexbilz.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"